"""change category type to enum

Revision ID: ff5b18b27c09
Revises: 
Create Date: 2026-02-25 20:41:55.474797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5b18b27c09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('INCOME', 'EXPENSE', name='transactiontype'),
               existing_nullable=False,
               postgresql_using="type::transactiontype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=sa.Enum('INCOME', 'EXPENSE', name='transactiontype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###